### ISSUE TITLE
concurrentqueue/concurrentqueue.h: No such file or direct

### ISSUE THREAD

**Issue by guanxiaoguan** [Qihoo360/evpp#101]
![image](https://user-images.githubusercontent.com/19222332/32480854-ba346d12-c3cb-11e7-9c11-651d56516552.png)

**Comment by guanxiaoguan** [comment]
concurrentqueue/concurrentqueue.h
是某个库的文件么？make 编译报错。

**Comment by zieckey** [comment]
是按照quick_start来操作的么？ `git submodule update --init --recursive` 应该是这条命令没有执行。
https://github.com/Qihoo360/evpp/blob/master/docs/quick_start.md#download-the-source-code-of-evpp

**Comment by guanxiaoguan** [comment]
感谢，重新clone编译已经通过了，用了make，没有用make -j。
