### ISSUE TITLE
如何在EventLoop::Run之后加入TCPClient连接

### ISSUE THREAD

**Issue by DragonQuestHero** [Qihoo360/evpp#103]
例如连接上限为10
那么添加10条TCPClient到loop里面 然后RUN
如果中间有一条任务完成 断开连接.那么需要加入另一个TCPClient
但是在looprun之后,再添加进去的连接并无作用

**Comment by DragonQuestHero** [comment]
刚刚大概看了一眼http conn_pool的实现
似乎是一条连接对应一个LOOP?

**Comment by DragonQuestHero** [comment]
ummmm...
中午看了下源代码 原来是需要用loop_thread 而且threadpool也提供了
感觉设计还是很不错的
就是BUG有点多
如果什么时候能加上SSL部分 再完善API文档 相信一个就是一个非常不错的库了

**Comment by zieckey** [comment]
上面说 `就是BUG有点多` 麻烦帮忙具体指出来啊，我们好改进啊

**Comment by DragonQuestHero** [comment]
额 不是那个意思
只是我把示例代码趴下来 接上去试一下就直接debug断言了
所以潜意识觉得..哇 好多BUG
