### ISSUE TITLE
windows_port.h 导入lib部分个人觉得改一下比较好

### ISSUE THREAD

**Issue by feihongmeilian** [Qihoo360/evpp#114]
windows_port.h导入lib部分我认为的问题如下：
1、没有区分debug和release版本，链接evpp时会报错。
2、当使用libevent2时，并不需要引入eventd.lib
3、glog在windows下静态库的编译项目名叫libglog_static
综上，以下是我的设置：

// We must link against these libraries on windows platform for Visual Studio IDE
#ifdef H_OS_WINDOWS

#ifndef EVPP_EXPORTS
#ifdef _DEBUG
#pragma comment(lib, "evpp_staticd.lib")
#else
#pragma comment(lib, "evpp_static.lib")
#endif
#endif

#pragma comment(lib, "Ws2_32.lib")

#ifdef _DEBUG
#pragma comment(lib, "libglog_staticd.lib")
#ifdef H_LIBEVENT_VERSION_14
#pragma comment(lib, "eventd.lib")
#else
#pragma comment(lib, "event_cored.lib") // libevent2.0
#pragma comment(lib, "event_extrad.lib") // libevent2.0
#endif
#else
#pragma comment(lib, "libglog_static.lib")
#ifdef H_LIBEVENT_VERSION_14
#pragma comment(lib, "event.lib")
#else
#pragma comment(lib, "event_core.lib") // libevent2.0
#pragma comment(lib, "event_extra.lib") // libevent2.0
#endif
#endif

#endif

**Comment by feihongmeilian** [comment]
可能只是我的习惯问题

**Comment by zieckey** [comment]
欢迎提PR
