### ISSUE TITLE
sockets.cc文件下对于inet_ntop及inet_pton的调用，导致xp下无法使用

### ISSUE THREAD

**Issue by feihongmeilian** [Qihoo360/evpp#116]
建议用 evutil_inet_ntop及evutil_inet_pton 替换掉，因为evpp已经使用了libevent里evutil.c下的socket_pair实现；并且，替换后 evpp就可以完美运行在xp下了

**Comment by zieckey** [comment]
感谢建议。欢迎提PR。

**Comment by feihongmeilian** [comment]
好的
