### ISSUE TITLE
window7旗舰版evpp多线程间由于pipe导致假死

### ISSUE THREAD

**Issue by robin-fei** [Qihoo360/evpp#127]
![1](https://user-images.githubusercontent.com/7486514/35609718-65999e24-0699-11e8-8855-11c5e3caacd7.jpg)
如上图，Notify后没有DoPendingFunctors执行，请问是怎么回事，给点思路。
ps：工作线程数20

**Comment by robin-fei** [comment]
还有cpu占用有点高，运行见后把机器资源耗光了，见下图
![2](https://user-images.githubusercontent.com/7486514/35609866-1b71b1e6-069a-11e8-8d21-9ee458405388.jpg)

**Comment by zieckey** [comment]
有测试代码吗？请参考这个：https://zhuanlan.zhihu.com/p/20752519

**Comment by robin-fei** [comment]
@zieckey ，测试程序是一个很简单的httpServer，如下：

#include "stdafx.h"
#include <mutex>
#include <boost/noncopyable.hpp>
#include <evpp/http/http_server.h>
#include <string>
#include "logging.h"


void OnHandle(evpp::EventLoop* loop,
	const evpp::http::ContextPtr& ctx,
	const evpp::http::HTTPSendResponseCallback& cb);

int main() {
	// init socket library
	WSADATA  Ws;
	if (WSAStartup(MAKEWORD(2, 2), &Ws) != 0) {
		throw "initialize WSA error";
	}

	google::InitGoogleLogging("");
	google::SetLogDestination(google::GLOG_INFO, "./logs/hub-info");
	google::SetLogDestination(google::GLOG_WARNING, "./logs/hub-warn");
	google::SetLogDestination(google::GLOG_ERROR, "./logs/hub-err");
	google::SetLogDestination(google::GLOG_FATAL, "./logs/hub-fatal");

    evpp::http::Server server(20);
    std::vector<int> ports = { 8088 };
    server.Init(ports);
    server.RegisterDefaultHandler(&OnHandle);
	server.Start();

	while (!server.IsStopped()) {
		usleep(20);
	}

    return 0;
}

void OnHandle(evpp::EventLoop* loop,
	const evpp::http::ContextPtr& ctx,
	const evpp::http::HTTPSendResponseCallback& cb) {

	ctx->set_response_http_code(200);

	std::string path = ctx->uri();
	LOG_INFO << "handle " << path;
	if (path == std::string("/ok.htm")) { // health check
        cb(std::string("ok"));
        LOG_INFO << "end handle";
		return;
	}
}

客户端：curl http://localhost:8088/ok.htm

**Comment by robin-fei** [comment]
在本机mac 10.12.6上编译出bin，运行了1+ day后没有出现假死现象，可以说明，win平台的evpp有bug，无法使用
