### ISSUE TITLE
Websocket Support?

### ISSUE THREAD

**Issue by aharonamir** [Qihoo360/evpp#146]
Hi , I am testing your webserver ,
So far it is very good , I even put it inside docker, works perfect.
Are you going to support websocket like [Boost.beast](https://github.com/boostorg/beast)?

**Comment by zieckey** [comment]
Thanks for you jobs for docker and testing.
Now, we have no plan to support websocket.

**Comment by aharonamir** [comment]
Thanks.

**Comment by gocpplua** [comment]
> Hi , I am testing your webserver ,
> So far it is very good , I even put it inside docker, works perfect.
> Are you going to support websocket like [Boost.beast](https://github.com/boostorg/beast)?

where is the dockerfile
