### ISSUE TITLE
Simple makefile for built libraries

### ISSUE THREAD

**Issue by lonnieOST** [Qihoo360/evpp#149]
Hello,

Let me first just say that I have recently built evpp along with the examples and tests on my Ubuntu 16.04 system and had no problems.

The software seems to be extremely fast and I like that a lot as I am going to try and use it for a middleware project that I am starting.

To that end, I would like to ask if there is a simple Makefile somewhere that I could use as a template in that I have the libraries built now, but want to use the examples/echo/httpecho code as my baseline for the multithreaded application and I do not know how to easily setup a makefile for just that project.

Any help would be greatly appreciated.
Thanks

**Comment by lonnieOST** [comment]
Hello,

On a follow-up, I just found a bit of information on "evmc" which seems to be the library behind evpp from what I can tell, so maybe I need to work on a Makefile for that library to be used with the httpecho code.

Cheers

**Comment by lonnieOST** [comment]
Hello,

I am trying to get a feel for evpp and to try and figure out a simple Linux (Ubuntu 16.04) Makefile so that I can build just one of the examples independently, but I cannot seem to even locate the "include" files that are needed to compile things and only found 1 of them.

Any ideas?

Do I need the EVPP or EVMC to compile against?

Thanks

**Comment by lonnieOST** [comment]
found the header now, but still not sure about how to setup a simple make file for the examples.
Thanks

**Comment by lonnieOST** [comment]
Is there, by chance any documentation on the methods in the class files?

**Comment by lonnieOST** [comment]
More Updates -----

Turns out that the "examples/echo/httpecho" does not return the full body of the message for some reason:

lonnie@spartan:~$ curl "http://localhost:29099/?q=solar%20panels&categories=general&format=json&lang=en&pageno=1"
func=DefaultHandler OK ip=127.0.0.1
 uri=/
 body=

I need to be able to extract "q=solar%20panels&categories=general&format=json&lang=en&pageno=1" into parts:

q=solar%20panels
categories=general
format=json
lang=en
pageno=1

Any ideas on this?
Thanks

**Comment by zieckey** [comment]
we use cmake to generate a Makefile

**Comment by lonnieOST** [comment]
Hello,

I am actually now using the existing build for the "simple proxy" and want
to add some more sources to be compiled with the "main.cc".

Where can I add those in your complex make?
Thanks.

**Comment by lonnieOST** [comment]
Hello,

I have been searching all over the evpp code but cannot seem to locate the
solution.

In the

examples/http/simple_proxy

directory, there is the "main.cc" code which builds nicely and I am using
it as a basis for my project while building it in its default location.

Everything builds nicely so far, but I have a question and could use your
help.

I am adding an additional file "gason.cc" to that directory in which the
simple_proxy "main.cc" will use.

My problem is that I do not know where to add the "gason.cc" file
information within the CMAKE structure so that it can be built into an
object file that can be linked with the simple_proxy main.cc code and ask
for your help to please tell me how to add that time into the build for
that main.cc

I have expanded upon the simple_proxy main.cc to need the functions and
methods contained within the gason.cc which will have the gason.hpp file
included from within the same directory.

Any assistance that you could provide would be greatly appreciated.
Thanks and have a great day.

**Comment by zieckey** [comment]
You need to learn the usage of CMAKE. Have fun.

**Comment by lonnieOST** [comment]
Thanks,

I figured out the CMAKE system.

**Comment by gerald-dotcom** [comment]
> we use cmake to generate a Makefile

The makefile you are using very odd and hard to grasp.
