### ISSUE TITLE
最新版的能直接编译过？

### ISSUE THREAD

**Issue by andylau004** [Qihoo360/evpp#157]
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc: In function ‘int evpp::sock::CreateUDPServer(int)’:
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc:93:50: error: ‘to_string’ is not a member of ‘std’
     std::string addr = std::string("0.0.0.0:") + std::to_string(port);
                                                  ^
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc: In function ‘bool evpp::sock::SplitHostPort(const char*, std::string&, int&)’:
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc:155:12: error: ‘atoi’ is not a member of ‘std’
     port = std::atoi(&a[index + 1]);
            ^
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc: In function ‘std::string evpp::sock::ToIPPort(const sockaddr_storage*)’:
/home/fy/WorkDir/ldd_work/c++_downwork/evpp/evpp/sockets.cc:219:37: error: ‘to_string’ is not a member of ‘std’
         saddr.append(":", 1).append(std::to_string(port));
                                     ^
evpp/CMakeFiles/evpp_concurrentqueue_static.dir/build.make:374: recipe for target 'evpp/CMakeFiles/evpp_concurrentqueue_static.dir/sockets.cc.o' failed
make[2]: *** [evpp/CMakeFiles/evpp_concurrentqueue_static.dir/sockets.cc.o] Error 1
CMakeFiles/Makefile2:97: recipe for target 'evpp/CMakeFiles/evpp_concurrentqueue_static.dir/all' failed
make[1]: *** [evpp/CMakeFiles/evpp_concurrentqueue_static.dir/all] Error 2
Makefile:162: recipe for target 'all' failed

fy@fy-ubuntu:~/WorkDir/ldd_work/c++_downwork/evpp/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu6' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu6) 
 

GCC 版本是支持C11的。

**Comment by zieckey** [comment]
怎么编译的？系统环境和编译步骤麻烦贴一下。

**Comment by andylau004** [comment]
可以了。重新打了个　ｄｏｃｋｅｒ　环境。
没问题。
