### ISSUE TITLE
How to properly stop a TCPServer?

### ISSUE THREAD

**Issue by jvalenciag** [Qihoo360/evpp#16]
I am implementing a service that uses a TCPServer running in other thread, it needs to do some processing after the server has stoped, but when Stop() is called the program hangs.

**Comment by zieckey** [comment]
Thank you for using `evpp`.
Please paste the sample code that can produce the your problem.

And we suggest that you can read the unit test code `testTCPServerSilenceShutdown`  at here [https://github.com/Qihoo360/evpp/blob/master/test/tcp_server_test.cc#L72-L82](https://github.com/Qihoo360/evpp/blob/master/test/tcp_server_test.cc#L72-L82). This tests the `TCPServer` to stop silently.

**Comment by zieckey** [comment]
Any updates?

**Comment by jvalenciag** [comment]
I was trying to stop the server when SIGINT or SIGTERM were recieved with the next function.
 ```cpp
evpp::EventLoop* loop;
evpp::TCPServer* server_ptr;
static void s_signal_handler(int signal_value) {
    loop->Stop(); //using only this: error on server destructor
    server_ptr->Stop(); //using only this: program hangs
}
```
Finally I arrived to a solution by calling Stop in both loop and server in that order.
In the test unit the Reset method is called in both loop and server to stop, what is the difference between Stop and Reset? I guess Reset makes possible to reuse the objects, is only that?

**Comment by zieckey** [comment]
We should stop TCPServer and after then, we can stop EventLoop, and lastly we call Reset to release the memory of the objects.

Please try the following code.  See https://github.com/Qihoo360/evpp/blob/master/test/tcp_server_test.cc#L87-L97

```C++
    std::unique_ptr<evpp::EventLoop> loop(new evpp::EventLoop);
    std::unique_ptr<evpp::TCPServer> tsrv(new evpp::TCPServer(loop.get(), addr, "tcp_server", 2));
    bool rc = tsrv->Init();
    rc = tsrv->Start();
    loop->RunAfter(evpp::Duration(1.0), [&tsrv, &loop]() { tsrv->Stop(); loop->Stop(); });
    loop->Run();
    loop.reset();
    tsrv.reset();
```

**Comment by jvalenciag** [comment]
So Stop has to be called inside the loop with a RunAfter necessarily?

**Comment by zieckey** [comment]
No, that's not necessary. You can another example.

1. We can stop the EventLoop in it's own thread immediately : [https://github.com/Qihoo360/evpp/blob/master/benchmark/post_task/post_task2.cc#L60](https://github.com/Qihoo360/evpp/blob/master/benchmark/post_task/post_task2.cc#L60) 
2. We also can stop the EventLoop in another thread : [https://github.com/Qihoo360/evpp/blob/master/benchmark/post_task/post_task6.cc#L59](https://github.com/Qihoo360/evpp/blob/master/benchmark/post_task/post_task6.cc#L59)

**Comment by jvalenciag** [comment]
Thank you for the help.
