### ISSUE TITLE
evpp在vs2017的mfc工程中报内存泄漏

### ISSUE THREAD

**Issue by 0to1** [Qihoo360/evpp#162]
我在一个mfc的项目中引用evpp，刚开始测试时我是在纯C++项目上测试的，没有太留意内存泄漏的问题。测试通后，我就花了两三天时间把项目的部分通信用evpp重写了，解决测试时发现有大量的内存泄漏问题。
刚开始还以为是其他地方的问题导致了内存泄漏，但最终定位到时evpp的内存泄漏。
并且evpp在一个新建的mfc项目中，只是简单使用也会有内存泄漏。
比如，引用头文件
#include <evpp/event_loop.h>
然后在函数中使用如下代码
std::shared_ptr<evpp::EventLoop> loop(new evpp::EventLoop);
程序退出时就会有内存泄漏。
拿测试用的代码进行测试也是同样是情况。

我的开发环境如下：
Windows版本： Windows10
Visual Studio版本： 15.7.4
Microsoft .Net Framewrok版本：4.7.03056
Windows SDK 版本：10.0.16299.0
![image](https://user-images.githubusercontent.com/5407516/42983874-d6b4e250-8c1b-11e8-83e4-83d9c1dd1bd8.png)

请问这是什么原因引起的，能否帮忙分析下哪个地方最有可能出问题。

**Comment by 0to1** [comment]
去除对glog/logging.h的依赖，就没有这个问题，应该是glog导致的。

**Comment by adou28** [comment]
会导致溢出的send 函数：`void evpp::TCPConn::Send(const void* d, size_t dlen);`

**Comment by adou28** [comment]
好吧，我发现是我傻x了，内存增大是正常的，因为压力测试下，outputBuffer的capacity变大了～并不是内存溢出
