### ISSUE TITLE
Multiple acception will cause "what():  basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by ckyang** [Qihoo360/evpp#164]
Hello, I'm trying to make TCP server with multiple accept implementation while referring to following sample code:

https://github.com/Qihoo360/evpp/blob/master/examples/multi_accept/main.cc

Inside OnMessage(), we use msg->NextString(length) to get what we want to read, just like traditional socket read().

However, when executing in multi-threaded environment (more than 20 threads), exception will be thrown like following then program is terminated:

`terminate called after throwing an instance of 'std::logic_error'`
`what():  basic_string::_M_construct null not valid`

If possible, could anyone please give some hint about how to use evpp correctly?

For example, in the sample code only TCPServer::Start() be called while we don't know if TCPServer::Stop() is needed also?

And, are the member functions of evpp::Buffer thread-safe?

Thanks a lot for the answer!

**Comment by feihongmeilian** [comment]
evpp::Buffer is non-thread-safe.

You can use the Buffer member function to manipulate integers.

For strings, I recommend using the data and size interface directly.Then call Skip function to notify Buffer.

**Comment by feihongmeilian** [comment]
void net::Client::Info(evpp::Buffer *msg)
{
    while (msg->length() > 0)
    {
        //read message head
        if (message_id_ == 0)
        {
            if (msg->length() < HEAD_SIZE)
            {
                break;
            }
            message_len_ = msg->ReadInt32();
            message_len_ -= HEAD_SIZE;
            message_id_ = msg->ReadInt32();
        }

        if (msg->size() < message_len_)
        {
            break;
        }

        const auto listener = server_->GetListener(message_id_);
        if (listener != nullptr)
        {
            listener(shared_from_this(), msg->data(), message_len_);
        }
        else
        {
			conn_->Close();
            return;
        }

        msg->Skip(message_len_);
        message_id_ = 0;
    }
}


Just a simple example
