### ISSUE TITLE
evnsq bug 报告

### ISSUE THREAD

**Issue by xiongbanban** [Qihoo360/evpp#168]
evnsq 在接收函数中错误判断buffer的size和message size的大小，写越界，导致消息丢失
git diff如下：
--- a/apps/evnsq/nsq_conn.cc
+++ b/apps/evnsq/nsq_conn.cc
@@ -14,6 +14,8 @@
 #include "client.h"
 #include "producer.h"

 namespace evnsq {
 static const std::string kNSQMagic = "  V2";
 static const std::string kOK = "OK";
@@ -99,7 +101,7 @@ void NSQConn::OnRecv(const evpp::TCPConnPtr& conn, evpp::Buffer* buf) {
     while (buf->size() > 4) {
         size_t size = buf->PeekInt32();

--        if (buf->size() < size) {
++       if (buf->size() < size + 4) {
             // need to read more data
             return;
         }
将会修复这个问题

**Comment by zieckey** [comment]
欢迎提PR，谢谢反馈。
