### ISSUE TITLE
evpp::Buffer 类应该增加 <unsigned char> API来处理字节流

### ISSUE THREAD

**Issue by hug2008** [Qihoo360/evpp#169]
充分考虑服务应用范围，如物联网等TCP协议，
丰富 evpp::Buffer 数据提取接口，
而不是统统按照字符串来处理。

**Comment by hug2008** [comment]
没有的
evpp::Buffer 的API更多的是以 std::string 和 const char* 返回类型作为数据提取接口；
我考虑的应用场景是物联网服务，硬件交互应用场景。
数据处理一般都是二进制的，如硬件指令、视频、图像、音频帧数据等....
显然  std::string 和 const char* 是不适合的。例如下面的数据：
![tim 20180823172633](https://user-images.githubusercontent.com/11781819/44517233-b6476580-a6f9-11e8-99ff-29f42b54f8bc.png)

**Comment by feihongmeilian** [comment]
硬件交互更应该对字节码以及字符串有深刻的认识，字符串只是计算机解释给人看的时候的一种约定，这种约定规定把0当作字符串的结束符，对于机器来说，这些都是字节码。

也就是char*  对机器来说，他就是块内存而已，只是你自己的认知不深把它当做了字节码。

Buffer里既然有指向某块内存的指针，又能返回可读写这块内存的长度，怎么解释这块内存就是你的事了。既然如此，为什么会有char* 不能表述的数据？你认为的unsigned char* 与char* 的差距又在哪？我的char* 指向的内存难道不能全是0吗？

你该补习计算机组成原理了
