### ISSUE TITLE
TCPClient Crash when disconnect on ConnectionCallback

### ISSUE THREAD

**Issue by aijyo** [Qihoo360/evpp#172]
crash scene:

![image](https://user-images.githubusercontent.com/7956449/46995843-0d434700-d14d-11e8-944d-53ce1d6e6b31.png)

reason:
Just as the img show, when Connector::HandleWrite::conn_fn_(chan_->fd(), laddr)(line 154) deal with user ConnectionCallback, conn is disconnected, timer_ has been reset 。 So some strategies must be taken to deal with such situations... eg: recheck connect state, or asyn disconnect...

![image](https://user-images.githubusercontent.com/7956449/46996257-95761c00-d14e-11e8-9693-13fd2830959b.png)

client code:
![image](https://user-images.githubusercontent.com/7956449/46995940-69a66680-d14d-11e8-91b6-5e8687c7c971.png)

server code:
![image](https://user-images.githubusercontent.com/7956449/46995923-5abfb400-d14d-11e8-9224-75f407ffe70c.png)

**Comment by aijyo** [comment]
> Please paste the code (server and client) which can reproduce this crash.
just as follow...

client code:
		void TCPConnectTest(const std::string strAddr/* = "127.0.0.1:10080"*/)
		{
			evpp::EventLoop loop;
			evpp::TCPClient client(&loop, strAddr, "TestClient");
			client.SetConnectionCallback([&loop, &client](const evpp::TCPConnPtr& conn) {
				bool bConnect = conn->IsConnected();
				client.Disconnect();
				loop.Stop();
			});
			client.SetMessageCallback([](const evpp::TCPConnPtr& conn, evpp::Buffer* buf) {
				std::string strMsg = buf->NextAllString();
			});
			client.Connect();
			loop.Run();

			int  nCount = evpp::GetActiveEventCount();
		}

server code:
int main(void)
{
	net::Init();
	std::string strAddr = "127.0.0.1:10080";
	int nThreadNum = std::thread::hardware_concurrency() * 2 + 2;

	evpp::EventLoop loop;
	evpp::TCPServer server(&loop, strAddr, "TCPServer", nThreadNum);

	server.SetMessageCallback([](const evpp::TCPConnPtr& conn,
		evpp::Buffer* msg) {
		conn->Send(msg);
	});

	server.SetConnectionCallback([](const evpp::TCPConnPtr& conn) {
		if (conn->IsConnected()) {
			LOG_INFO << "A new connection from " << conn->remote_addr();
		}
		else {
			LOG_INFO << "Lost the connection from " << conn->remote_addr();
		}
	});
	server.Init();
	server.Start();
	loop.Run();

	net::UnInit();
	return 0;
}

net code:

#ifdef WIN32
#include <WinSock2.h>

#pragma comment(lib, "Ws2_32.lib")
#endif

namespace net
{
	static void Init()
	{
#ifdef WIN32
		// Initialize Winsock 2.2
		WSADATA wsaData;
		int err = WSAStartup(MAKEWORD(2, 2), &wsaData);

		if (err) {
			std::cout << "WSAStartup() failed with error: %d" << err;
		}
#endif
	}

	static void UnInit()
	{
#ifdef WIN32
		system("pause");
		WSACleanup();
#endif
	}
}

**Comment by zieckey** [comment]
The code below can reproduce this problem:

```C++
{
    const std::string strAddr = "qup.f.360.cn:80";
    evpp::EventLoop loop;
    evpp::TCPClient client(&loop, strAddr, "TestClient");
    client.SetConnectionCallback([&loop, &client](const evpp::TCPConnPtr& conn) {
        bool bConnect = conn->IsConnected();
        client.Disconnect();
        loop.Stop();
                                 });
    client.SetMessageCallback([](const evpp::TCPConnPtr& conn, evpp::Buffer* buf) {
        std::string strMsg = buf->NextAllString();
                              });
    client.Connect();
    loop.Run();
}
```

**Comment by zieckey** [comment]
The right usage is :
```C++
{
    const std::string strAddr = "www.12306.cn:80";
    evpp::EventLoop loop;
    evpp::TCPClient client(&loop, strAddr, "TestClient");
    client.SetConnectionCallback([&loop, &client](const evpp::TCPConnPtr& conn) {
        if (conn->IsConnected()) {
            auto f = [&]() {
                client.Disconnect();
                loop.Stop();
            };
            loop.RunAfter(evpp::Duration(1.0), f);
        }
    }
    );
    client.SetMessageCallback([](const evpp::TCPConnPtr& conn, evpp::Buffer* buf) {
        std::string strMsg = buf->NextAllString();
                              });
    client.Connect();
    loop.Run();
}
```

**Comment by zieckey** [comment]
Please see https://github.com/Qihoo360/evpp/commit/d95ace5fb30e00d504ef2563f7cd57759fecc9b5

**Comment by aijyo** [comment]
> Please have a look: [d95ace5](https://github.com/Qihoo360/evpp/commit/d95ace5fb30e00d504ef2563f7cd57759fecc9b5)
> 
> @aijyo

got it. thanks
