### ISSUE TITLE
tcpserver是否有TCPConnPtr读空闲检测

### ISSUE THREAD

**Issue by airx** [Qihoo360/evpp#201]
java netty有这个机制，设置一个读空闲的时间，如果某个TCPConnPtr超过这个时间没有收到数据，会触发读空闲的处理回调，这样好处理这个TCPConnPtr心跳超时等问题，非常方便。
evpp该怎么做，可以比较优雅的达到上述功能？

**Comment by ZhongHeyuan** [comment]
这个机制在应用层做可以 。evpp 深度参考陈硕的muduo网络库 ，可以看看陈硕写的《用 Timing wheel 踢掉空闲连接》
muduo库例子里面也有相关实现muduo/examples/idleconnection/。希望能帮到你

**Comment by airx** [comment]
> 这个机制在应用层做可以 。evpp 深度参考陈硕的muduo网络库 ，可以看看陈硕写的《用 Timing wheel 踢掉空闲连接》
> muduo库例子里面也有相关实现muduo/examples/idleconnection/。希望能帮到你

谢谢，我看下
