### ISSUE TITLE
关于DoPendingFunctors中的一些问题

### ISSUE THREAD

**Issue by pengwang7** [Qihoo360/evpp#210]
std::vector<Functor> functors;
    {
        std::lock_guard<std::mutex> lock(mutex_);
        notified_.store(false);
        pending_functors_->swap(functors);
        DLOG_TRACE << "pending_functor_count_=" << pending_functor_count_ << " PendingQueueSize=" << GetPendingQueueSize() << " notified_=" << notified_.load();
    }
    DLOG_TRACE << "pending_functor_count_=" << pending_functor_count_ << " PendingQueueSize=" << GetPendingQueueSize() << " notified_=" << notified_.load();
    for (size_t i = 0; i < functors.size(); ++i) {
        functors[i]();
        --pending_functor_count_;
    }

上面的代码中， pending_functors_->swap(functors);pending_functors_的大小就为0了，是不是与pending_functor_count_不符合？另外在StopInLoop（）中，为什么要调用两次f（），而调用f中，应该先判断为null比较好吧

**Comment by andylau004** [comment]
1.  swap 的作用
是为防止 上层调用插入仿函数，到pending_functors_ 内，而当前线程正在阻塞执行，而导致的卡住；
2.  f() 调用两遍，可能是防止pending_functors_ 内还有函数没执行；


@pengwang7 @shgxwxl

**Comment by pengwang7** [comment]
@andylau004 OK，谢谢
