### ISSUE TITLE
请问UDP报文是否支持大包（大于1500）字节的数据传输？

### ISSUE THREAD

**Issue by luoyouchun** [Qihoo360/evpp#216]

**Comment by Flymachine** [comment]
MTU值默认是1500，是网关，路由器等的默认设置，不是服务器能控制的。TCP的MSS值可以算出是1460，超过这个数就分片了，也就是TCP分包的依据。
UDP如果不在意数据包的到达顺序和传输中错误率的话，你分包大小设成多少都无所谓。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Eric <notifications@github.com&gt;
发送时间: 2019年9月27日 10:03
收件人: Qihoo360/evpp <evpp@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[Qihoo360/evpp] 请问UDP报文是否支持大包（大于1500）字节的数据传输？ (#216)

**Comment by mdsf22** [comment]
我印象中， 
1.  UDP最大支持64K
2.  MTU 1500， 超过这个值就分片，这个是由IP层控制的， 到达顺序不重要，最后都是要重组的

**Comment by Flymachine** [comment]
最大包长是我疏忽了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mdsf22 <notifications@github.com&gt;
发送时间: 2019年9月27日 10:40
收件人: Qihoo360/evpp <evpp@noreply.github.com&gt;
抄送: Flymachine <1473152048@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Qihoo360/evpp] 请问UDP报文是否支持大包（大于1500）字节的数据传输？ (#216)

**Comment by shgxwxl** [comment]
根据生产环境的经验，建议udp报文控制在一个不要分片的大小比较好
