### ISSUE TITLE
关于线程安全的疑问

### ISSUE THREAD

**Issue by aijyo** [Qihoo360/evpp#236]
1、在同一个eventloop 当中，存在N个conn 的时候，当在onmessagecallback 回调的时候 调用另一个conn是不是线程安全的？
代码逻辑差不多是这样的：
class server
{
void onmessagecallback(conn, msg)
{
  conn2 = conns[2];   // conn 收到消息的时候，触发事件调用其它的conn send msg 这里是不是线程安全的？
  conn2.send(msg);
}

list conns_;
}

更进一步我看到有eventloopthreadpool，如果上面的操作是线程安全的，那么在同一个threadpool的 eventloop里面的conn是不是线程安全的呢？

**Comment by andylau004** [comment]
安全。
在同一个 eventloop 内触发的 conn 读操作是 单线程内顺序执行。

**Comment by aijyo** [comment]
那也就是说，如果是eventloopthreadpool 里面的loop 因为不是一个线程 其实还是得自己加锁保证线程安全？

**Comment by aijyo** [comment]
那也就是说，如果是eventloopthreadpool 里面的loop 因为不是一个线程 其实还是得自己加锁保证线程安全？

**Comment by andylau004** [comment]
event thread pool 里面多个event loop，每个 loop在一个独立的event thread内，
每个eventloop负责 IO 复用N个套接字。所以，理论上，每个套接字都在单线程内工作；所以不存在多线程操作同一个socket

可以看看 muduo那本书。，evpp基于 muduo写的；

**Comment by aijyo** [comment]
> event thread pool 里面多个event loop，每个 loop在一个独立的event thread内，
> 每个eventloop负责 IO 复用N个套接字。所以，理论上，每个套接字都在单线程内工作；所以不存在多线程操作同一个socket
> 
> 可以看看 muduo那本书。，evpp基于 muduo写的；

我看了源码之后，大概知道了，因为我要用这个做一个数据转发工作，然后，可能从A eventloop 的一个socket 转到B event loop 的socket，也就是存在跨线程的问题，已解决
