### ISSUE TITLE
API/ABI changes review for evpp

### ISSUE THREAD

**Issue by lvc** [Qihoo360/evpp#24]
May be useful for tracking API/ABI changes in the library: https://abi-laboratory.pro/tracker/timeline/evpp/

The report is created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker

Thank you.

![evpp-1](https://cloud.githubusercontent.com/assets/1517837/24827249/eff46e32-1c57-11e7-88d0-1f73442d8e7c.png)

![evpp-2](https://cloud.githubusercontent.com/assets/1517837/24827253/f452999a-1c57-11e7-9f7e-5c75c270b0e0.png)

## Environment
* Linux x86_64
* GCC 4.9
* evpp 0.1.0 and higher

**Comment by zieckey** [comment]
Great. Thanks very much.
