### ISSUE TITLE
无法检测到客户端是否已断开连接

### ISSUE THREAD

**Issue by fjqisba** [Qihoo360/evpp#279]
假如一个客户端连接上服务端后，使用宽带拨号切换IP，在短时间内再次连接上服务端，此时服务端无法检测到原先的ip_port已经断开连接，这要如何处理。。。

**Comment by netfbi** [comment]
加个心跳看看

**Comment by fjqisba** [comment]
后面改用asio2解决了，这个库貌似会自动检测连接断开
