### ISSUE TITLE
TCPServer 的 thread_num 有什么作用 ? ，为什么要建立多个 EventLoopThreadPool ?  1 和 4 有什么区别吗？

### ISSUE THREAD

**Issue by netfbi** [Qihoo360/evpp#305]
// @param thread_num - The working thread count
    TCPServer(EventLoop* loop,
              const std::string& listen_addr/*ip:port*/,
              const std::string& name,
              uint32_t thread_num);

这个 working thread count ，指的是 EventLoopThreadPool 的个数，为什么要建立多个？ 1 和 4 有什么区别吗？

**Comment by netfbi** [comment]
这个 working thread 可以替代 处理业务的线程吗？

**Comment by zieckey** [comment]
这并不是指EventLoopThreadPool的个数，是指EventLoopThreadPool这个线程池里面的线程数
