### ISSUE TITLE
evnsq is not ready forever when it connects nsqd in some case，even nsqd is ok

### ISSUE THREAD

**Issue by liwei-ch** [Qihoo360/evpp#33]
tag:0.3.0
场景：重启nsqd；切换nsq对象，出现evnsq一直不ready的现象；

E0413 15:35:31.297906 121534 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.297941 121541 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298004 121573 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.297988 121572 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.297940 121539 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298244 121519 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298007 121574 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298313 121542 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298290 121543 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298413 121576 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.297991 121540 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298322 121544 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298416 121545 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298013 121575 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298435 121578 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298676 121549 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298750 121580 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298422 121548 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298835 121520 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298735 121547 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.299043 121518 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298773 121552 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298760 121579 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298758 121551 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298310 121577 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298785 121581 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298804 121515 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298480 121582 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298856 121553 batch_producer.cc:248] nsq is not ready
E0413 15:35:31.298643 121546 batch_producer.cc:248] nsq is not ready

**Comment by zieckey** [comment]
是否还有重现？

**Comment by zieckey** [comment]
未能重现。
