### ISSUE TITLE
你们编译会不会报错。

### ISSUE THREAD

**Issue by yuangu** [Qihoo360/evpp#38]
**问题：**
我使用VS2015和VS2017编译X64总是报错错误。基本上都是

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“int evutil_socketpair(int,int,int,intptr_t [])”: 无法将参数 4 从“int [2]”转换为“intptr_t []”	evpp_static	C:\code\evpp\evpp\libevent_watcher.cc	120	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“void event_set(event *,intptr_t,short,void (__cdecl *)(intptr_t,short,void *),void *)”: 无法将参数 4 从“overloaded-function”转换为“void (__cdecl *)(intptr_t,short,void *)”	evpp_static	C:\code\evpp\evpp\fd_channel.cc	54	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“void event_set(event *,intptr_t,short,void (__cdecl *)(intptr_t,short,void *),void *)”: 无法将参数 4 从“void (__cdecl *)(int,short,void *)”转换为“void (__cdecl *)(intptr_t,short,void *)”	evpp_static	C:\code\evpp\evpp\libevent_watcher.cc	228

**产生的原因**
然后我们看一下定义vcruntime.h（VS系统提供的）中的intptr_t定义。
// Definitions of common types
#ifdef _WIN64
    typedef unsigned __int64 size_t;
    typedef __int64          ptrdiff_t;
    typedef __int64          intptr_t;
#else
    typedef unsigned int     size_t;
    typedef int              ptrdiff_t;
    typedef int              intptr_t;
#endif

event2 中的util.h定义

#ifdef _WIN32
#define evutil_socket_t intptr_t
#else
#define evutil_socket_t int
#endif

**Comment by yuangu** [comment]
看看要不要把用的int改成intptr_t

**Comment by zieckey** [comment]
看起来应该是把socket fd的类型由`int`修改为`evutil_socket_t`，更合适一点。

欢迎提PR。
谢谢

**Comment by zieckey** [comment]
有最新进展么？

**Comment by yuangu** [comment]
哥们，等我熟悉一下代码塞，哈哈…………

**Comment by zieckey** [comment]
支持windows x64需要修改的内容比较多，请帮忙review一下代码b2535d79fffb1cacd6d9b013ad5fea3b0284ae47
