### ISSUE TITLE
Any way to send data from an udp server?

### ISSUE THREAD

**Issue by jvalenciag** [Qihoo360/evpp#4]
I need to implement a two way udp based communication, but I don't now how to send data from an udp_server.

**Comment by zieckey** [comment]
Please see [https://github.com/Qihoo360/evpp/blob/master/evpp/udp/udp_message.h#L44-L67](https://github.com/Qihoo360/evpp/blob/master/evpp/udp/udp_message.h#L44-L67).

We treat an UDP package `send` is a atomic operation.

**Comment by zieckey** [comment]
You need to create udp socket. Please take a look at this book  http://www.unpbook.com/

**Comment by jvalenciag** [comment]
I mean, want to use the socket from an udp_server.

**Comment by zieckey** [comment]
Please take a look at this two source files :
https://github.com/Qihoo360/evpp/blob/master/examples/echo/udpecho/main.cc#L43
https://github.com/Qihoo360/evpp/blob/master/test/udp_server_test.cc#L13

**Comment by zieckey** [comment]
Any update?

**Comment by jvalenciag** [comment]
I think it would be useful a way to create or configure an udp_message from an UDP server.
