### ISSUE TITLE
TCPServer和client是长连接还是短连接

### ISSUE THREAD

**Issue by wangxin5355** [Qihoo360/evpp#40]
我没看见代码有发送心跳包保持连接，请问tcp是那种连接

**Comment by zieckey** [comment]
是长连接。但心跳包由上层应用来发，因为每种应用的tcp协议可能不一样。

**Comment by wangxin5355** [comment]
再问个事情，发生消息和接收消息时，是否可以设置偏移字节

**Comment by zieckey** [comment]
很抱歉，没明白。

**Comment by wangxin5355** [comment]
我就想问问在这个框架下如何处理粘包和拆包

**Comment by zieckey** [comment]
必然框架自己处理好了啊。

**Comment by zieckey** [comment]
收包时，evpp会把数据包缓存到 `TCPConn::input_buffer_` 中，发包时，如果数据没有完全发送完，会顺序缓存到 `TCPConn::input_buffer_`中，当下次可写事件到来时，优先发送之前缓存的数据。

**Comment by wangxin5355** [comment]
包头是否有记录包的大小？

**Comment by zieckey** [comment]
这是上层应用层的TCP协议的事情。每种TCP协议都不一样。例如http1.x和http2的协议就不一样，其记录TCP包大小的方式就不一样。

**Comment by zieckey** [comment]
还有问题吗？
