### ISSUE TITLE
怎么获取每次事件发生的时间戳

### ISSUE THREAD

**Issue by dreamtraveler** [Qihoo360/evpp#46]
我知道 evp::Timesamp:now() 可以获取当前时间，但是这个方法每次是一个系统调用，太费了，我想本身eventloop 的每次loop已经计算过一次时间了，io事件发生时应该把这个时间传给上层，我看到tcp_server.h有一个注释是这么写的
//     server.SetMessageCallback([](const evpp::TCPConnPtr& conn,
//                                  evpp::Buffer* msg,
//                                  evpp::Timestamp ts) 
但是实际上第三个参数evpp::Timestamp ts已经没用了，是改过版本的问题吗，还有定时器
evpp::InvokeTimerPtr EventLoop::RunEvery(Duration interval, const Functor& f) 
也没有把当前时间传出来，我要得到当前时间，又要找系统要一遍，既然eventloop已经得到当前时间了，应用层就不该再算一次。

**Comment by zieckey** [comment]
是的。在最最开始的设计中，MessageCallback的第三个参数就是一个时间搓。但后来，我们考虑到我们当前的实际情况没有用，就在v0.3版本的时候去掉了。

由于我们底层是libevent，libevent也没有导出类似接口。因此，我们也没有很高效的实现方案。

如有必要，请自行在上层调用`evp::Timesamp:now()`（底层是gettimeofday）来获取当前系统时间戳，我们相信一般而言，gettimeofday应该不会是系统的性能瓶颈。

多说一句：
在 x86-64 平台上，gettimeofday 不是系统调用，而是在用户态实现的（搜 vsyscall），没有上下文切换和陷入内核的开销。 具体可以参考线两篇文章。
1. http://blog.csdn.net/russell_tao/article/details/7185588
2. http://blog.csdn.net/Solstice/article/details/6173563

**Comment by dreamtraveler** [comment]
好的，谢谢解答
