### ISSUE TITLE
vcpkg的问题？

### ISSUE THREAD

**Issue by Dzlua** [Qihoo360/evpp#49]
使用vcpkg安装后，命名空间 evpp::httpc 不能使用，头文件没有 httpc下得

**Comment by zieckey** [comment]
看来是vcpkg打包的问题，如果着急的话，可以尝试去 https://github.com/Microsoft/vcpkg 看看。我尽快修正这个问题。
谢谢反馈。

**Comment by Dzlua** [comment]
我有编译evpp，所以直接使用了src里边的头文件。

**Comment by zieckey** [comment]
可以，这样使用没问题。

**Comment by zieckey** [comment]
已提PR给vcpkg了 https://github.com/Microsoft/vcpkg/pull/1328

**Comment by zieckey** [comment]
还有问题么？

**Comment by yuangu** [comment]
看一下可不可以用这个来管理第三方依赖。

https://github.com/cppan/cppan

**Comment by zieckey** [comment]
没用用过cppan，后续可以研究一下，谢谢。当前vcpkg是微软官方维护的。

**Comment by zieckey** [comment]
没用用过cppan，后续可以研究一下，谢谢。当前vcpkg是微软官方维护的。
