### ISSUE TITLE
cmake编译evnsq时提示说找不到utils

### ISSUE THREAD

**Issue by 2013211450** [Qihoo360/evpp#50]
fatal error: concurrentqueue/concurrentqueue.h: No such file or directory
请问这个是什么依赖？
=================================
上面那个问题我已经解决了。 但是编译安装完evpp后再安装evnsq时cmake时报错。
evpp文件夹下的CMakeLists中有相同的include语句， 但是可以成功编译。。。不明白为什么。
CMake Error at CMakeLists.txt:12 (include):
  include could not find load file:

    utils

CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    packages

**Comment by zieckey** [comment]
可以使用 `tools/release-build.sh` 来编译release版本，如果没有错误，会在 /the/path/toevpp/build-release/packages 下面生成几个安装包，包括rpm、tar.gz等。

**Comment by 2013211450** [comment]
运行./release-build.sh 提示报错
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/CLionProjects/evpp
+ make -j
make: *** No targets specified and no makefile found.  Stop.

**Comment by 2013211450** [comment]
好像原因是我的cmake出了点问题， 虽然指定了makefile的生成路径， 但是他还是生成到了CMakeLists的同目录下？ 请问这个问题是cmake的什么配置出了问题么？

**Comment by zieckey** [comment]
OK
