### ISSUE TITLE
how to run example_evnsq_producer?

### ISSUE THREAD

**Issue by jjqcat** [Qihoo360/evpp#57]
Hi, I'm learn evpp and what's the steps to run example evnsq_producer?
Thanks

**Comment by zieckey** [comment]
follow https://github.com/Qihoo360/evpp/blob/master/docs/quick_start.md please.

**Comment by jjqcat** [comment]
I have compiled all examples, and the step 2 is that we must run NSQD server? but how to implemnt NSQD server?

**Comment by zieckey** [comment]
You need to  know what is a NSQ, please take a look at http://nsq.io 
Do you really want to run example_evnsq_producer ? or just want to run a tcp server and client examples ?

**Comment by jjqcat** [comment]
you are right, I want to check how fast TCP server and client. the test result is about 7MB/s on my local LAN with debug version. how to speed it?

**Comment by zieckey** [comment]
You should run benchmark_pingpong_client and benchmark_pingpong_server to test the TCP network throughput.

**Comment by jjqcat** [comment]
ohh, evpp supports multi-processes ,where is example about it? Thanks.

**Comment by zieckey** [comment]
evpp supports multi-threads. benchmark_pingpong_client and benchmark_pingpong_server are the examples.
