### ISSUE TITLE
How do I exit loop.run()? 

### ISSUE THREAD

**Issue by caistd** [Qihoo360/evpp#59]
// @brief Join the thread. If you forget to call this method,
// it will be invoked automatically in the destruct method ~EventLoopThread().
// @note DO NOT call this method from any of the working thread.
void Join();

EventLoopThread::~EventLoopThread() {
DLOG_TRACE << "loop=" << event_loop_;
assert(IsStopped());
Join();
}
Causes the thread to fail

**Comment by zieckey** [comment]
Use `loop.Stop()` to exit. For example:
```C++
    auto f = [&loop]() {
        loop.Stop();
    };
    loop.RunAfter(evpp::Duration(10.0), f);
```

**Comment by caistd** [comment]
Is there a manual?

**Comment by zieckey** [comment]
Sorry, we don't have a manual. Please read the example source codes.

**Comment by caistd** [comment]
loop.RunAfter(evpp::Duration(1.0), [&loop] { loop.Stop(); });  
is ok
    auto f = [&loop]() {
        loop.Stop();
    };
    loop.RunAfter(evpp::Duration(10.0), f);
[ &loop] lambda Unable to capture variables why

**Comment by zieckey** [comment]
```C++
```

**Comment by zieckey** [comment]
```C++
auto f = &loop {
    loop.Stop();
};
```

That lambda's format is wrong. The right way to define a lambda is :
```C++
    auto f = [&loop]() {
        loop.Stop();
    };
```

**Comment by caistd** [comment]
thankyou
Is there any other way to solve it? 
and What's the difference between event_loop_thread.h and event_loop_thread_pool.h  in multiple threads ?

**Comment by zieckey** [comment]
EventLoopThread is one thread, EventLoopThreadPool is a thread pool which holds multi threads.

**Comment by caistd** [comment]
How to create multithreaded？

**Comment by zieckey** [comment]
Please see the API. e.g. `evpp::TCPServer(&loop, addr, "TCPEcho", 12)` will create a thread pool with 12 threads in it.

**Comment by caistd** [comment]
when i  create a thread  ,while it run to loop.run();we should use loop.RunAfter(evpp::Duration(10.0), f) can exit run ;We also can stop the EventLoop in another thread  but  in this e.g  it stop at  p.Wait();

-----------------------------------------------
int main(int argc, char* argv[]) {

    int thread_count = 2;

    long long post_count = 10000;



    if (argc == 3) {

        thread_count = std::atoi(argv[1]);

        post_count = std::atoll(argv[2]);

    } else {

        printf("Usage : %s <thread-count> <post-count>\n", argv[0]);

        return 0;

    }



    PostTask p(thread_count, post_count);

    p.Start();

    p.Wait();

 LOG_WARN << argv[0] << " thread_count=" << thread_count << " post_count=" << post_count << " use time: " << p.use_time() << " seconds\n";

    return 0;

}
-------------------------------------------

**Comment by zieckey** [comment]
what is `PostTask`?

**Comment by caistd** [comment]
Updated

**Comment by caistd** [comment]
// @brief Join the thread. If you forget to call this method,
    // it will be invoked automatically in the destruct method ~EventLoopThread().
    // @note DO NOT call this method from any of the working thread.
    void Join();
---------------------------------------
EventLoopThread::~EventLoopThread() {
    DLOG_TRACE << "loop=" << event_loop_;
    assert(IsStopped());
    Join();
}
--------------------------------------------------------------------
Causes the thread to fail
