### ISSUE TITLE
mac下的build问题

### ISSUE THREAD

**Issue by 2013211450** [Qihoo360/evpp#68]
make时报错： evpp/evpp/sockets.cc:27:78: error: operator '!' has no right operand
evpp/evpp/sockets.cc:33:31: error: invalid conversion from 'int' to 'const char*' [-fpermissive]
     const char* s = strerror_r(e, buf, sizeof(buf) - 1); // GNU-specific

编译器版本：The CXX compiler identification is GNU 5.4.0
make版本： GNU Make 3.81

。 请问可以删除掉这两段宏定义么？

**Comment by zieckey** [comment]
嗯，针对MAC的测试我们不太充分。MAC下应该使用`XSI-compliant`这个分支逻辑，但预编译条件不对，导致编译错误。欢迎提PR解决。

**Comment by zieckey** [comment]
https://github.com/Qihoo360/evpp/commit/01e8c01fb7d9b6c7fb1f1f2336e355bb375dc727 已经解决。请再试试。
