### ISSUE TITLE
会支持TCP重连吗

### ISSUE THREAD

**Issue by yezhibin000** [Qihoo360/evpp#70]
evpp库会支持TCP重连吗？

**Comment by supermario1990** [comment]
@yezhibin000 支持的，你好好看看代码和example

**Comment by zieckey** [comment]
支持。TCPClient对象默认就是断线自动重连的，有参数可以关闭该选项。详情请参考源码。

**Comment by yezhibin000** [comment]
谢谢，看了下源码TCP客户端的接口，的确有参数auto_reconnect_、reconnect_interval_ 以及connecting_timeout_来控制重连的策略。
另外提个小问题：我编译代码时，由于编译说找不到glog.lib（已编译了win64 Debug下的glog-0.3.3版本静态库），我只能屏蔽掉了glog库。屏蔽掉glog库后编译通过。是不是glog库要0.3.4版本的才能通过？

**Comment by zieckey** [comment]
详细编译步骤请参考 https://github.com/Qihoo360/evpp/blob/master/docs/quick_start_windows_with_visualstudio.md
