### ISSUE TITLE
在LINUX虚拟机下编译并使用EVPP的问题

### ISSUE THREAD

**Issue by Guozht** [Qihoo360/evpp#76]
LINUX：centos6.0
evpp：0.7.0
使用CMake编译出libevpp_static.a静态库
但是在使用时编译报错
[root@localhost TestEvpp]# g++ -o test test.c -L.-levpp_static
/tmp/ccUOaevr.o: In function `httpc::HandleHTTPResponse(std::shared_ptr<evpp::httpc::Response> const&, evpp::EventLoopThread*, char*)':
test.c:(.text+0x1b1): undefined reference to `evpp::httpc::Request::~Request()'
/tmp/ccUOaevr.o: In function `main':
test.c:(.text+0x1fb): undefined reference to `evpp::EventLoopThread::EventLoopThread()'
test.c:(.text+0x23b): undefined reference to `evpp::EventLoopThread::Start(bool, std::function<int ()()>, std::function<int ()()>)'
test.c:(.text+0x268): undefined reference to `evpp::EventLoopThread::loop() const'
test.c:(.text+0x373): undefined reference to `google::LogMessage::LogMessage(char const*, int)'
test.c:(.text+0x382): undefined reference to `google::LogMessage::stream()'
test.c:(.text+0x39e): undefined reference to `google::LogMessage::~LogMessage()'
test.c:(.text+0x42d): undefined reference to `evpp::httpc::Request::Execute(std::function<void ()(std::shared_ptr<evpp::httpc::Response> const&)> const&)'
test.c:(.text+0x467): undefined reference to `evpp::EventLoopThread::Stop(bool)'
test.c:(.text+0x47d): undefined reference to `google::LogMessage::LogMessage(char const*, int)'
test.c:(.text+0x489): undefined reference to `google::LogMessage::stream()'
test.c:(.text+0x4a2): undefined reference to `google::LogMessage::~LogMessage()'
test.c:(.text+0x520): undefined reference to `evpp::EventLoopThread::~EventLoopThread()'
test.c:(.text+0x5bf): undefined reference to `google::LogMessage::~LogMessage()'
test.c:(.text+0x5ec): undefined reference to `google::LogMessage::~LogMessage()'
test.c:(.text+0x614): undefined reference to `evpp::EventLoopThread::~EventLoopThread()'
/tmp/ccUOaevr.o: In function `evpp::Duration::Duration(double)':
test.c:(.text._ZN4evpp8DurationC2Ed[_ZN4evpp8DurationC5Ed]+0x10): undefined reference to `evpp::Duration::kSecond'
/tmp/ccUOaevr.o: In function `evpp::httpc::PostRequest::PostRequest(evpp::EventLoop*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, evpp::Duration)':
test.c:(.text._ZN4evpp5httpc11PostRequestC2EPNS_9EventLoopERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_NS_8DurationE[_ZN4evpp5httpc11PostRequestC5EPNS_9EventLoopERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_NS_8DurationE]+0x37): undefined reference to `evpp::httpc::Request::Request(evpp::EventLoop*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, evpp::Duration)'
collect2: 错误：ld 返回 1

**Comment by Guozht** [comment]
g++ -static test.c -L. -lglog -levpp_static -levent -levent_core -levent_extra -o test
/usr/bin/ld: cannot find -lm
collect2: 错误：ld 返回 1

**Comment by RobsXiao** [comment]
why? same question
