### ISSUE TITLE
http请求参数获取问题

### ISSUE THREAD

**Issue by sumory** [Qihoo360/evpp#77]
好像默认没有提供以下几个API?

- 获取http请求类型：GET/POST/PUT...
- 获取post请求参数，现在只有一个`ctx->body()`可以用？
- 获取完整的URL

**Comment by zieckey** [comment]
1. 没有暴露出“GET/POST/PUT ..."等方法，如有必要的话，后续可以增加
2. post我们认为暴露一个 ctx->body() 足够了，有更详细需求，可以应用层自行解析
3. 完整的URL通过`ctx->original_uri()` 获取

**Comment by sumory** [comment]
嗯，我自己[包了一下](https://github.com/sumory/ciao/blob/master/ciao/evpp_driver/evpp_request.h#L19)
