### ISSUE TITLE
libevpp_static.a静态库的使用问题

### ISSUE THREAD

**Issue by Guozht** [Qihoo360/evpp#80]
我该怎么写编译指令，比如一个testevpp.cpp文件，怎么写？比如g++ -static -o test testevpp.cpp -levpp_static。正确的应该怎么写，都依赖什么库文件（glog libevent gflags）？

**Comment by inter169** [comment]
假如evpp headers在/usr/local/include，lib在这/usr/local/lib/，
centos7下使用原生的依赖库（ yum install glog* gflags* libevent2*），编译命令为：
g++ main.cc -std=c++11 -o main.out -I /usr/local/include /usr/local/lib/libevpp_static.a  -lglog -lgflags -levent

```
ldd ./main.out 
        linux-vdso.so.1 =>  (0x00007ffdf874a000)
        libglog.so.0 => /lib64/libglog.so.0 (0x00007f9aac73b000)
        libgflags.so.2.1 => /lib64/libgflags.so.2.1 (0x00007f9aac51a000)
        libevent-2.0.so.5 => /lib64/libevent-2.0.so.5 (0x00007f9aac2d1000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9aabfc8000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9aabcc6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9aabaaf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f9aab6ee000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9aab4d2000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9aac97a000)
```

**Comment by Guozht** [comment]
@inter169 多谢，已经编译过了。再问一下glog、event、gflags也使用静态库的话编译命令应该怎么写？因为程序如果发布的话，总不能让用户把glog、event、gflags也安装一遍，使用动态库连接吧.....

**Comment by inter169** [comment]
有些依赖库（glog）centos7 yum rpm包本身是没有.a的，除非源码编译这些依赖库，看能否生成静态库.a
然后编译命令加上静态依赖库（***.a）
如果不成也可以考虑把这些第三方依赖库so+binary做个rpm/tgz安装包 、或docker基础镜像吧？
