### ISSUE TITLE
Android平台怎么使用这个库

### ISSUE THREAD

**Issue by Guozht** [Qihoo360/evpp#83]
Android平台怎么编译使用这个库？

**Comment by zieckey** [comment]
我们没有搞过，理论上是可以移植过去的。

**Comment by Guozht** [comment]
@zieckey 我也知道可以移植过去，毕竟EVPP用的都是标准库，但是咋移植弄得我很挠头。。。不知道怎么编译，交叉编译的话，我试了一下貌似不好用，要不然就是我用的交叉编译链不对QAQ，求助！！！有没有移植过Android平台的大佬。。

**Comment by chris118** [comment]
现在支持android了么

**Comment by zieckey** [comment]
没有专门搞过这方面的编译环境

**Comment by chinafei** [comment]
目前还没有计划支持websocket么,已经三年过去了...

**Comment by gocpplua** [comment]
> 我们没有搞过，理论上是可以移植过去的。

现在搞定了吗
