### ISSUE TITLE
是否有API文档或者手册?

### ISSUE THREAD

**Issue by DragonQuestHero** [Qihoo360/evpp#92]
代码虽然简单易懂
但还是看下文档或者手册来的更快一些
还有就是貌似没看到关于SSL连接和https的部分代码

**Comment by zieckey** [comment]
很抱歉，没有文档。看例子代码吧。
目前也的确没有SSL、HTTPS相关代码

**Comment by DragonQuestHero** [comment]
那现在是否支持SSL和HTTPS呢?
建议做个文档或者API手册吧 当然只是个建议而已 因为写那个东西比较麻烦

**Comment by zieckey** [comment]
当前情况下，SSL或HTTPS可以通过nginx做代理转发。

**Comment by DragonQuestHero** [comment]
可惜我这边情况不太允许使用代理转发
多谢回复
have nice day
