### ISSUE TITLE
UdpClient链接错误码代码位置错了

### ISSUE THREAD

**Issue by smallb** [Qihoo360/evpp#93]
![image](https://user-images.githubusercontent.com/3250973/32214887-3a72f4c4-be5b-11e7-91b4-f9678353966c.png)
这里错误码获取到一直都是0.
因为获取到的是Close()操作成功之后的错误码。。。

应该将日志函数放在Close函数之前。

**Comment by zieckey** [comment]
感谢反馈，欢迎提PR修复。

**Comment by feihongmeilian** [comment]
这个addrlen的计算是不是也有问题，应该根据addr->sa_family的值来判断后计算是ip4的size还是ip6的size吧，没有环境不好测试……

**Comment by zieckey** [comment]
fixed https://github.com/Qihoo360/evpp/pull/94
